### ISSUE TITLE
I'm getting an error installing and loading bootstraplib to run your app locally

### ISSUE THREAD

**Issue by sowusu08** [duke-shiny-ed/OutlierApp#1]
Here's what it says --
"Warning in install.packages :
  package ‘bootstraplib’ is not available (for R version 3.6.2)"

I think 3.6.2 is the latest version

**Comment by grace-hub** [comment]
I'm actually getting that too -- bootstraplib won't install on my RStudio. Might be more a problem with the package or my RStudio or something rather than an issue with the app, but I'm not quite sure how to get it to install at the moment
