### ISSUE TITLE
Explore - Identify outliers 

### ISSUE THREAD

**Issue by matackett** [duke-shiny-ed/OutlierApp#7]
- [x] Rename tab to "Fit a model" 
- [x] Include text on side (see Issue #6 )
- [x] Formatting for model output 

  - Use kable to format tables
  - Remove bullet points
  - Rename "Model using original observations"  and "Model using original and new observations"
  - Use `theme_bw()` for the plot
  - Make label on plot labels
 
@seanmtli

**Comment by seanmtli** [comment]
kable already formatted tables I think? 

not sure what you mean by label on plot labels so i just put (medi) and (bav) next to the axis of plot

**Comment by matackett** [comment]
I think the kable formatting is defaulting to markdown tables, so you need to include `format = "html"` in the kable function. Then on the user interface side, output the table as  htmlOutput

**Comment by matackett** [comment]
oh that should say make plot labels bigger / increase the font size on the axis labels and title.
